language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install: "pip install -r requirements_test.txt"
# command to run tests
script: python test_project/manage.py test rh